// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchChangeIDOKCode is the HTTP code returned for type PatchChangeIDOK
const PatchChangeIDOKCode int = 200

/*
PatchChangeIDOK Success

swagger:response patchChangeIdOK
*/
type PatchChangeIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPatchChangeIDOK creates PatchChangeIDOK with default headers values
func NewPatchChangeIDOK() *PatchChangeIDOK {

	return &PatchChangeIDOK{}
}

// WithPayload adds the payload to the patch change Id o k response
func (o *PatchChangeIDOK) WithPayload(payload string) *PatchChangeIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch change Id o k response
func (o *PatchChangeIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchChangeIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
