// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchChangeIDHandlerFunc turns a function with the right signature into a patch change ID handler
type PatchChangeIDHandlerFunc func(PatchChangeIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchChangeIDHandlerFunc) Handle(params PatchChangeIDParams) middleware.Responder {
	return fn(params)
}

// PatchChangeIDHandler interface for that can handle valid patch change ID params
type PatchChangeIDHandler interface {
	Handle(PatchChangeIDParams) middleware.Responder
}

// NewPatchChangeID creates a new http.Handler for the patch change ID operation
func NewPatchChangeID(ctx *middleware.Context, handler PatchChangeIDHandler) *PatchChangeID {
	return &PatchChangeID{Context: ctx, Handler: handler}
}

/*
	PatchChangeID swagger:route PATCH /change/{id} patchChangeId

PatchChangeID patch change ID API
*/
type PatchChangeID struct {
	Context *middleware.Context
	Handler PatchChangeIDHandler
}

func (o *PatchChangeID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchChangeIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
