// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/go-swagger/go-swagger/fixtures/bugs/2782/codegen/models"
)

// NewPostChangeIDParams creates a new PostChangeIDParams object
//
// There are no default values defined in the spec.
func NewPostChangeIDParams() PostChangeIDParams {

	return PostChangeIDParams{}
}

// PostChangeIDParams contains all the bound params for the post change ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostChangeID
type PostChangeIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ID string
	/*array to post
	  Required: true
	  In: body
	*/
	MyArray []models.Item
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostChangeIDParams() beforehand.
func (o *PostChangeIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []models.Item
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("myArray", "body", ""))
			} else {
				res = append(res, errors.NewParseError("myArray", "body", "", err))
			}
		} else {

			// validate array of body objects
			for i := range body {
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}

			if len(res) == 0 {
				o.MyArray = body
			}
		}
	} else {
		res = append(res, errors.Required("myArray", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PostChangeIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ID = raw

	return nil
}
