// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostChangeIDOKCode is the HTTP code returned for type PostChangeIDOK
const PostChangeIDOKCode int = 200

/*
PostChangeIDOK Success

swagger:response postChangeIdOK
*/
type PostChangeIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostChangeIDOK creates PostChangeIDOK with default headers values
func NewPostChangeIDOK() *PostChangeIDOK {

	return &PostChangeIDOK{}
}

// WithPayload adds the payload to the post change Id o k response
func (o *PostChangeIDOK) WithPayload(payload string) *PostChangeIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post change Id o k response
func (o *PostChangeIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChangeIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
