// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostChangeIDHandlerFunc turns a function with the right signature into a post change ID handler
type PostChangeIDHandlerFunc func(PostChangeIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChangeIDHandlerFunc) Handle(params PostChangeIDParams) middleware.Responder {
	return fn(params)
}

// PostChangeIDHandler interface for that can handle valid post change ID params
type PostChangeIDHandler interface {
	Handle(PostChangeIDParams) middleware.Responder
}

// NewPostChangeID creates a new http.Handler for the post change ID operation
func NewPostChangeID(ctx *middleware.Context, handler PostChangeIDHandler) *PostChangeID {
	return &PostChangeID{Context: ctx, Handler: handler}
}

/*
	PostChangeID swagger:route POST /change/{id} postChangeId

PostChangeID post change ID API
*/
type PostChangeID struct {
	Context *middleware.Context
	Handler PostChangeIDHandler
}

func (o *PostChangeID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostChangeIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
