// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHealthCheckReader is a Reader for the GetHealthCheck structure.
type GetHealthCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /health_check] GetHealthCheck", response, response.Code())
	}
}

// NewGetHealthCheckOK creates a GetHealthCheckOK with default headers values
func NewGetHealthCheckOK() *GetHealthCheckOK {
	return &GetHealthCheckOK{}
}

// GetHealthCheckOK describes a response with status code 200, with default header values.
//
// Server OK
type GetHealthCheckOK struct {
}

// IsSuccess returns true when this get health check o k response has a 2xx status code
func (o *GetHealthCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get health check o k response has a 3xx status code
func (o *GetHealthCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get health check o k response has a 4xx status code
func (o *GetHealthCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get health check o k response has a 5xx status code
func (o *GetHealthCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get health check o k response a status code equal to that given
func (o *GetHealthCheckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get health check o k response
func (o *GetHealthCheckOK) Code() int {
	return 200
}

func (o *GetHealthCheckOK) Error() string {
	return fmt.Sprintf("[GET /health_check][%d] getHealthCheckOK", 200)
}

func (o *GetHealthCheckOK) String() string {
	return fmt.Sprintf("[GET /health_check][%d] getHealthCheckOK", 200)
}

func (o *GetHealthCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
