// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Timeofday
A silly time-of-day


    Schemes:
      http
    Host: localhost
    BasePath: /timeofday/v1
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
