// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A silly time-of-day",
    "title": "Timeofday",
    "version": "0.1.0"
  },
  "basePath": "/timeofday/v1",
  "paths": {
    "/time": {
      "get": {
        "operationId": "GetTime",
        "parameters": [
          {
            "type": "string",
            "description": "Timezone to return",
            "name": "timezone",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/TimeOfDay"
            }
          },
          "404": {
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      },
      "post": {
        "operationId": "PostTime",
        "parameters": [
          {
            "name": "Timezone",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Timezone"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/TimeOfDay"
            }
          },
          "404": {
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotFound": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "TimeOfDay": {
      "type": "object",
      "properties": {
        "timeOfDay": {
          "type": "string"
        }
      }
    },
    "Timezone": {
      "type": "object",
      "properties": {
        "timezone": {
          "type": "string",
          "minLength": 3
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A silly time-of-day",
    "title": "Timeofday",
    "version": "0.1.0"
  },
  "basePath": "/timeofday/v1",
  "paths": {
    "/time": {
      "get": {
        "operationId": "GetTime",
        "parameters": [
          {
            "type": "string",
            "description": "Timezone to return",
            "name": "timezone",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/TimeOfDay"
            }
          },
          "404": {
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      },
      "post": {
        "operationId": "PostTime",
        "parameters": [
          {
            "name": "Timezone",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Timezone"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/TimeOfDay"
            }
          },
          "404": {
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "NotFound": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "TimeOfDay": {
      "type": "object",
      "properties": {
        "timeOfDay": {
          "type": "string"
        }
      }
    },
    "Timezone": {
      "type": "object",
      "properties": {
        "timezone": {
          "type": "string",
          "minLength": 3
        }
      }
    }
  }
}`))
}
