// Code generated by go-swagger; DO NOT EDIT.

// Package restapi ordering security requirements
//
//	verify that generated code keeps a stable order of security requirements
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/x-yaml
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
