// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "verify that generated code keeps a stable order of security requirements",
    "title": "ordering security requirements",
    "version": "1.0.0"
  },
  "paths": {
    "/config/{instance}": {
      "put": {
        "consumes": [
          "application/x-yaml"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Connect"
        ],
        "operationId": "config_put",
        "parameters": [
          {
            "type": "string",
            "x-exportParamName": "Instance",
            "description": "instance name",
            "name": "instance",
            "in": "path",
            "required": true
          },
          {
            "x-exportParamName": "Config",
            "description": "The Configuration",
            "name": "config",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "format": "binary"
            }
          },
          {
            "type": "string",
            "x-exportParamName": "ContentType",
            "description": "configuration MIME type",
            "name": "Content-Type",
            "in": "header"
          }
        ],
        "responses": {
          "204": {
            "description": "The configuration updated successfully"
          },
          "400": {
            "description": "Malformed YAML"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "verify that generated code keeps a stable order of security requirements",
    "title": "ordering security requirements",
    "version": "1.0.0"
  },
  "paths": {
    "/config/{instance}": {
      "put": {
        "consumes": [
          "application/x-yaml"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Connect"
        ],
        "operationId": "config_put",
        "parameters": [
          {
            "type": "string",
            "x-exportParamName": "Instance",
            "description": "instance name",
            "name": "instance",
            "in": "path",
            "required": true
          },
          {
            "x-exportParamName": "Config",
            "description": "The Configuration",
            "name": "config",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string",
              "format": "binary"
            }
          },
          {
            "type": "string",
            "x-exportParamName": "ContentType",
            "description": "configuration MIME type",
            "name": "Content-Type",
            "in": "header"
          }
        ],
        "responses": {
          "204": {
            "description": "The configuration updated successfully"
          },
          "400": {
            "description": "Malformed YAML"
          }
        }
      }
    }
  }
}`))
}
