// Code generated by go-swagger; DO NOT EDIT.

package connect

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ConfigPutReader is a Reader for the ConfigPut structure.
type ConfigPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewConfigPutNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewConfigPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /config/{instance}] config_put", response, response.Code())
	}
}

// NewConfigPutNoContent creates a ConfigPutNoContent with default headers values
func NewConfigPutNoContent() *ConfigPutNoContent {
	return &ConfigPutNoContent{}
}

/*
ConfigPutNoContent describes a response with status code 204, with default header values.

The configuration updated successfully
*/
type ConfigPutNoContent struct {
}

// IsSuccess returns true when this config put no content response has a 2xx status code
func (o *ConfigPutNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this config put no content response has a 3xx status code
func (o *ConfigPutNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this config put no content response has a 4xx status code
func (o *ConfigPutNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this config put no content response has a 5xx status code
func (o *ConfigPutNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this config put no content response a status code equal to that given
func (o *ConfigPutNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the config put no content response
func (o *ConfigPutNoContent) Code() int {
	return 204
}

func (o *ConfigPutNoContent) Error() string {
	return fmt.Sprintf("[PUT /config/{instance}][%d] configPutNoContent", 204)
}

func (o *ConfigPutNoContent) String() string {
	return fmt.Sprintf("[PUT /config/{instance}][%d] configPutNoContent", 204)
}

func (o *ConfigPutNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewConfigPutBadRequest creates a ConfigPutBadRequest with default headers values
func NewConfigPutBadRequest() *ConfigPutBadRequest {
	return &ConfigPutBadRequest{}
}

/*
ConfigPutBadRequest describes a response with status code 400, with default header values.

Malformed YAML
*/
type ConfigPutBadRequest struct {
}

// IsSuccess returns true when this config put bad request response has a 2xx status code
func (o *ConfigPutBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this config put bad request response has a 3xx status code
func (o *ConfigPutBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this config put bad request response has a 4xx status code
func (o *ConfigPutBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this config put bad request response has a 5xx status code
func (o *ConfigPutBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this config put bad request response a status code equal to that given
func (o *ConfigPutBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the config put bad request response
func (o *ConfigPutBadRequest) Code() int {
	return 400
}

func (o *ConfigPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /config/{instance}][%d] configPutBadRequest", 400)
}

func (o *ConfigPutBadRequest) String() string {
	return fmt.Sprintf("[PUT /config/{instance}][%d] configPutBadRequest", 400)
}

func (o *ConfigPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
