// Code generated by go-swagger; DO NOT EDIT.

package connect

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewConfigPutParams creates a new ConfigPutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConfigPutParams() *ConfigPutParams {
	return &ConfigPutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConfigPutParamsWithTimeout creates a new ConfigPutParams object
// with the ability to set a timeout on a request.
func NewConfigPutParamsWithTimeout(timeout time.Duration) *ConfigPutParams {
	return &ConfigPutParams{
		timeout: timeout,
	}
}

// NewConfigPutParamsWithContext creates a new ConfigPutParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ConfigPutParams]
func NewConfigPutParamsWithContext(ctx context.Context) *ConfigPutParams {
	return &ConfigPutParams{
		Context: ctx,
	}
}

// NewConfigPutParamsWithHTTPClient creates a new ConfigPutParams object
// with the ability to set a custom HTTPClient for a request.
func NewConfigPutParamsWithHTTPClient(client *http.Client) *ConfigPutParams {
	return &ConfigPutParams{
		HTTPClient: client,
	}
}

/*
ConfigPutParams contains all the parameters to send to the API endpoint

	for the config put operation.

	Typically these are written to a http.Request.
*/
type ConfigPutParams struct {

	/* ContentType.

	   configuration MIME type
	*/
	ContentType *string

	/* Config.

	   The Configuration

	   Format: binary
	*/
	Config io.ReadCloser

	/* Instance.

	   instance name
	*/
	Instance string

	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ConfigPutParams]
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the config put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfigPutParams) WithDefaults() *ConfigPutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the config put params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfigPutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the config put params
func (o *ConfigPutParams) WithTimeout(timeout time.Duration) *ConfigPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the config put params
func (o *ConfigPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the config put params
//
// Deprecated: use the operation call with context to pass the context instead of [ConfigPutParams]
func (o *ConfigPutParams) WithContext(ctx context.Context) *ConfigPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the config put params
//
// Deprecated: use the operation call with context to pass the context instead of [ConfigPutParams]
func (o *ConfigPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the config put params
func (o *ConfigPutParams) WithHTTPClient(client *http.Client) *ConfigPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the config put params
func (o *ConfigPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the config put params
func (o *ConfigPutParams) WithContentType(contentType *string) *ConfigPutParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the config put params
func (o *ConfigPutParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithConfig adds the config to the config put params
func (o *ConfigPutParams) WithConfig(config io.ReadCloser) *ConfigPutParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the config put params
func (o *ConfigPutParams) SetConfig(config io.ReadCloser) {
	o.Config = config
}

// WithInstance adds the instance to the config put params
func (o *ConfigPutParams) WithInstance(instance string) *ConfigPutParams {
	o.SetInstance(instance)
	return o
}

// SetInstance adds the instance to the config put params
func (o *ConfigPutParams) SetInstance(instance string) {
	o.Instance = instance
}

// WriteToRequest writes these params to a swagger request
func (o *ConfigPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}
	}
	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	// path param instance
	if err := r.SetPathParam("instance", o.Instance); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
