// Code generated by go-swagger; DO NOT EDIT.

package connect

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConfigPutNoContentCode is the HTTP code returned for type ConfigPutNoContent
const ConfigPutNoContentCode int = 204

/*
ConfigPutNoContent The configuration updated successfully

swagger:response configPutNoContent
*/
type ConfigPutNoContent struct {
}

// NewConfigPutNoContent creates ConfigPutNoContent with default headers values
func NewConfigPutNoContent() *ConfigPutNoContent {

	return &ConfigPutNoContent{}
}

// WriteResponse to the client
func (o *ConfigPutNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ConfigPutBadRequestCode is the HTTP code returned for type ConfigPutBadRequest
const ConfigPutBadRequestCode int = 400

/*
ConfigPutBadRequest Malformed YAML

swagger:response configPutBadRequest
*/
type ConfigPutBadRequest struct {
}

// NewConfigPutBadRequest creates ConfigPutBadRequest with default headers values
func NewConfigPutBadRequest() *ConfigPutBadRequest {

	return &ConfigPutBadRequest{}
}

// WriteResponse to the client
func (o *ConfigPutBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
