// Code generated by go-swagger; DO NOT EDIT.

package connect

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConfigPutHandlerFunc turns a function with the right signature into a config put handler
type ConfigPutHandlerFunc func(ConfigPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConfigPutHandlerFunc) Handle(params ConfigPutParams) middleware.Responder {
	return fn(params)
}

// ConfigPutHandler interface for that can handle valid config put params
type ConfigPutHandler interface {
	Handle(ConfigPutParams) middleware.Responder
}

// NewConfigPut creates a new http.Handler for the config put operation
func NewConfigPut(ctx *middleware.Context, handler ConfigPutHandler) *ConfigPut {
	return &ConfigPut{Context: ctx, Handler: handler}
}

/*
	ConfigPut swagger:route PUT /config/{instance} Connect configPut

ConfigPut config put API
*/
type ConfigPut struct {
	Context *middleware.Context
	Handler ConfigPutHandler
}

func (o *ConfigPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewConfigPutParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
