// Code generated by go-swagger; DO NOT EDIT.

package connect

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewConfigPutParams creates a new ConfigPutParams object
//
// There are no default values defined in the spec.
func NewConfigPutParams() ConfigPutParams {

	return ConfigPutParams{}
}

// ConfigPutParams contains all the bound params for the config put operation
// typically these are obtained from a http.Request
//
// swagger:parameters config_put
type ConfigPutParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*configuration MIME type
	  In: header
	*/
	ContentType *string

	/*The Configuration
	  Required: true
	  In: body
	*/
	Config io.ReadCloser

	/*instance name
	  Required: true
	  In: path
	*/
	Instance string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewConfigPutParams() beforehand.
func (o *ConfigPutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindContentType(r.Header[http.CanonicalHeaderKey("Content-Type")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		o.Config = r.Body
	} else {
		res = append(res, errors.Required("config", "body", ""))
	}

	rInstance, rhkInstance, _ := route.Params.GetOK("instance")
	if err := o.bindInstance(rInstance, rhkInstance, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindContentType binds and validates parameter ContentType from header.
func (o *ConfigPutParams) bindContentType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ContentType = &raw

	return nil
}

// bindInstance binds and validates parameter Instance from path.
func (o *ConfigPutParams) bindInstance(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Instance = raw

	return nil
}
