
name: Publish docker

on:
  push:
    tags:
      - v*
    branches:
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  docker_dev:
    needs: [lint, build, test, codegen_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/goswagger/swagger
            ghcr.io/go-swagger/go-swagger
          tags: |
            type=ref,event=branch         # <- will update image with tag "master"
            type=sha                      # <- do we want an image for each commit?
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker meta
        id: meta
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/goswagger/swagger
            ghcr.io/go-swagger/go-swagger
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push dev
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            commit_hash=${{ github.sha }}
            tag_name=dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            commit_hash=${{ github.sha }}
            tag_name=${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}

  docker:
    needs: [lint, build, test, codegen_test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/goswagger/swagger
            ghcr.io/go-swagger/go-swagger
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            commit_hash=${{ github.sha }}
            tag_name=${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
