name: test-docker

# TODO: on workflow_call from test

on:
  pull_request:
    paths:
      - Dockerfile*

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker build
    uses: ./.github/workflows/build-docker.yaml
    with:
      push: false
